name: StudGo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.5.1  
  flutter_svg: ^0.18.0
  animator: ^2.0.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  provider: ^4.1.3+1
  url_launcher: ^5.6.0
  http: ^0.12.2
  skeleton_text: ^1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/activity_feed.svg
    - images/no_content.svg
    - images/search.svg
    - images/upload.svg
    - images/google_signin_button.png
    - images/studGO.png
    - images/studGO_01.svg
    - images/icons8-to-do-96.png
    - images/icons8-tick-box-32.png
    - images/icons8-tick-box-32(1).png
    - images/degree-fabric-light.png
    - images/Infinity-0.7s-200px.gif
    - images/icons8-news-96.png
    - images/px-tile-1920x1080.png
    - images/px-tile.png
    - images/icons8-google-code-96.png
    - images/codeforces.png
    - images/codechef1.png
    - images/google.png
    - images/leetcode.png
    - images/cp1.png
    - images/cp2.png
    - images/cp3.png
    - images/cp4.png
    - images/cp5.png
    - images/cp6.jpg
    - images/cp7.png
    - images/cp8.png
    - images/cp9.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Semravut
      fonts:
        - asset: fonts/Semravut.ttf
  #         style: italic 
    - family: Arvo
      fonts:
        - asset: fonts/Arvo.ttf
    - family: MavenPro
      fonts:
        - asset: fonts/MavenPro-Bold.ttf 
        # - asset: fonts/TrajanPro_Bold.ttf
        #   weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
